<?php

namespace App\Models;

use Eloquent;
use Illuminate\Database\Eloquent\Model;

class Userattention extends Eloquent
{
    /**
     * @var string
     * 表名称
     */
    protected $table='userattention';
    /**
     * @var array
     * 好友表
     */
    protected $fillable=[
        'user_id',
        'attention_userid',
        'status'
    ];

    /**
     * @return array
     *
     */
    public  function  rules(){
        return [
          'create'=>[
              'user_id'=>'required',
              'attention_userid'=>'required',
          ],
        ];
    }

    public function belongsToUser()
    {
        return parent::belongsTo('App\User'); // TODO: Change the autogenerated stub
    }
}
